FROM python:3.7-alpine


ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache --update --virtual .build-deps  build-base \
    gcc \
    tzdata && pip install --upgrade pip && \
    cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    echo "Europe/Moscow" > /etc/timezone


RUN mkdir /app

COPY ./app/backend/requirements.txt /app/requirements.txt

RUN pip install -U --no-cache-dir -r /app/requirements.txt

RUN find /usr/local \
        \( -type d -a -name test -o -name tests \) \
        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
        -exec rm -rf '{}' + &&\
    runDeps="$( \
        scanelf --needed --nobanner --recursive /usr/local \
                | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
                | sort -u \
                | xargs -r apk info --installed \
                | sort -u \
    )" \
    && apk add --virtual .rundeps $runDeps \
    && apk del --no-cache && apk del --no-cache .build-deps && rm -rf /var/cache/apk/*

COPY ./app/backend /app

RUN pip install /app

EXPOSE 8000


CMD ["python", "-m", "run_app"]
