FROM nginx:alpine 

RUN mkdir /app && \
    mkdir /tmp/log && \
    ln -sf /dev/stdout /tmp/log/access.log && \
    ln -sf /dev/stderr /tmp/log/error.log 
COPY --from=docker_example_frontend_app /app/dist /app
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf



CMD ["nginx-debug", "-g", "daemon off;"]